export default
{
    words: [
        "homosexualité",
        "gays",
        "lesbianisme",
        "lesbienne",
        "transgenre",
        "transphobe",
        "transsexuel",
        "transsexuelle",
        "transidentité",
        "trav",
        "trap",
        "travlo",
        "travelo",
        "goudou",
        "tantouze",
        "inverti",
        "gaypride",
        "homophobe",
        "homophobie",
        "PD",
        "homos",
        "tapette",
        "fiotte",
        "pédé",
        "enculé",
        "pédo",
        "\"lobby+lgbt\""
    ],
    flags: [
        "lgbt",
        "lgbt",
        "asexual",
        "bisexual",
        "aromantic",
        "nonbinary",
        "transgender",
        "pansexual"
    ]
}
