export default
{
    words: [
        "lgbt",
        "homosexualité",
        "gays",
        "lesbianisme",
        "lesbienne",
        "transgenre",
        "transphobe",
        "transsexuel",
        "transsexuelle",
        "transidentité",
        "non-binaire",
        // "\"non+binaire\"",
        // "\"non+binarité\"",
        // "\"non+binarité\"",
        "nb",
        "aroace",
        "aro",
        "ace",
        // "intersexualité",
        // "intersexuation",
        "intersexe",
        "hermaphrodite",
        "bi",
        "bisexuel",
        "bisexuelle",
        "pansexuel",
        // "pansexuelle",
        "panromantique",
        "trav",
        "trap",
        "travlo",
        "travelo",
        "goudou",
        "tantouze",
        "inverti",
        "gaypride",
        "homophobe",
        "homophobie",
        "PD",
        "homos",
        "tapette",
        "zoulette",
        "fiotte",
        "pédé",
        "enculé",
        "pédo",
        "\"lobby+lgbt\""
    ],
    flags: [
        "lgbt",
        "lgbt",
        "asexual",
        "bisexual",
        "aromantic",
        "nonbinary",
        "transgender",
        "pansexual"
    ]
}
